-- Initial seed Content for the Menu.
USE simply_falafel_db;

INSERT INTO menuItems(category, menuItem, style, price, createdAt, updatedAt)
VALUES
    ("Meal", "Falafel", "Pita", 6.75, now(), now()),
    ("Meal", "Falafel", "Platter", 9.99, now(), now()),
    ("Meal", "Beef Shawarma", "Pita", 7.40, now(), now()),
    ("Meal", "Beef Shawarma", "Platter", 12.99, now(), now()),
    ("Meal", "Chicken Shawarma", "Pita", 6.95, now(), now()),
    ("Meal", "Chicken Shawarma", "Platter", 11.99, now(), now()),
    ("Meal", "Beef & Chicken Shawarma", "Pita", 7.49, now(), now()),
    ("Meal", "Beef & Chicken Shawarma", "Platter", 13.99, now(), now()),
    ("Meal", "Kofta Kabob", "Pita", 7.99, now(), now()),
    ("Meal", "Kofta Kabob", "Platter", 12.99, now(), now()),
    ("Meal", "Chicken Kabob", "Pita", 6.99, now(), now()),
    ("Meal", "Chicken Kabob", "Platter", 12.99, now(), now()),
    ("Meal", "Salmon Kabob", "Pita", 9.40, now(), now()),
    ("Meal", "Salmon Kabob", "Platter", 14.99, now(), now()),
    ("Meal", "Veggie Kabob", "Pita", 6.95, now(), now()),
    ("Meal", "Veggie Kabob", "Platter", 9.99, now(), now()),
    ("Meal", "Combo Kabob", "Platter", 16.99, now(), now()),
    ("Meal", "Shish Tawook", "Pita", 6.99, now(), now()),
    ("Meal", "Shish Tawook", "Platter", 12.99, now(), now()),
    ("Meal", "Lamb Shank", "Platter", 14.99, now(), now()),
    ("Vegan", "White Beans", "Pita", 7.40, now(), now()),
    ("Vegan", "White Beans", "Platter", 12.99, now(), now()),
    ("Vegan", "Okra Chop", "Platter", 9.99, now(), now()),
    ("Kids", "Chicken Nuggets", "Platter", 5.99, now(), now()),
    ("Kids", "Chicken Strips", "Platter", 5.99, now(), now()),
    ("Salad", "'Greek Salad'", "Salad", 6.95, now(), now()),
    ("Salad", "Shawarma Salad", "Salad", 7.99, now(), now()),
    ("Salad", "Tabbouleh Salad", "Salad", 6.95, now(), now()),
    ("Salad", "Fatoush Salad", "Salad", 6.95, now(), now()),
    ("Soup", "Lentil Soup", "Soup", 3.95, now(), now()),
    ("Side", "Hummus", "Side", 4.95, now(), now()),
    ("Side", "Hummus +Shawarma", "Side", 7.45, now(), now()),
    ("Side", "Boba Ghanouj", "Side", 5.25, now(), now()),
    ("Side", "Falafel", "Side", 3.95, now(), now()),
    ("Side", "Stuffed Grape Leaves", "Side", 5.25, now(), now()),
    ("Side", "Rice", "Side", 2.95, now(), now()),
    ("Side", "French Fries", "Side", 2.95, now(), now()),
    ("Sweet", "Baklava", "Dessert", 3.95, now(), now()),
    ("Sweet", "Maamoul", "Dessert", 2.25, now(), now()),
    ("Drink", "Coke", "Soft Drink", 1.99, now(), now()),
    ("Drink", "Coke Zero", "Soft Drink", 1.99, now(), now()),
    ("Drink", "Pibb Xtra", "Soft Drink", 1.99, now(), now()),
    ("Drink", "Sprite", "Soft Drink", 1.99, now(), now()),
    ("Drink", "Minute Maid Lemonade", "Soft Drink", 1.99, now(), now()),
    ("Drink", "Powerade", "Soft Drink", 1.99, now(), now()),
    ("Drink", "Iced Tea (Unsweet)", "Tea", 1.25, now(), now()),
    ("Drink", "Iced Tea (Sweet)", "Tea", 1.25, now(), now()),
    ("Drink", "Bottled Water", "Water", 1.25, now(), now()),
    ("Drink", "Juice", "Juice", 2.75, now(), now()),
    ("Drink", "Laban: Yogurt Drink", "Specialty", 2.75, now(), now());